### PR TITLE
MH2

### PR DESCRIPTION
**Pull request by mainman879**
Adds all the MH2 token relations

### CODE REVIEW

**Comment by ebbit1q** [comment]
the new tokens can be found here https://magic.wizards.com/en/articles/archive/card-preview/tokens-modern-horizons-2-2021-06-03

we could also wait for scryfall to add the tokens but these seem to be high enough quality scans

**Review by ebbit1q — APPROVED** [review]
Looks good, tested, updated timestamp

**Comment by Psithief** [comment]
@ebbit1q Please squash pull requests before merging in the future.

**Comment by ebbit1q** [comment]
I have squashed them as you wish

**Pull request merged**
