### PR TITLE
Add documentation file

### PR DESCRIPTION
**Pull request by tooomm**
- [x] Remove example card from data file
- [x] Create new documentation file
    - [ ] Add dummy card
    - [ ] Add explanation about file structure and how relations work
    - [ ] Add explanation about various tags/attributes (include examples!)
    - [ ] Usage guidelines and best practices
- [ ] Link new file from current xml's
- [ ] Link to documentation in readme
- [ ] Remove notes from the wiki and link to the dedicated doc file instead

<br />

Useful resources:
- https://github.com/Cockatrice/Magic-Token/wiki#documentation
- https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets#to-add-your-own-custom-cards-follow-these-steps
- https://github.com/Cockatrice/Magic-Token/pull/119#issuecomment-922989535
- https://github.com/Cockatrice/Magic-Token/issues/111

### CODE REVIEW

**Comment by Psithief** [comment]
But I copy that when inserting tokens. 😢

**Comment by mainman879** [comment]
I see no reason to delete it from the file. Having it in the file is easier to use than having it on a dedicated wiki page, and people may reference the token files when learning to make their own custom xmls.

**Comment by tooomm** [comment]
>But I copy that when inserting tokens. 😢

I see, we are affecting and challenging the way you used to work with the file in many ways recently. Nothing personal. 🙈 

<br>

>I see no reason to delete it from the file. Having it in the file is easier to use than having it on a dedicated wiki page, and people may reference the token files when learning to make their own custom xmls.

In my opinion, a documentation should not be part of such a big file itself. Especially since it needs more than this dummy card. We can just not provide that in the file.

I know it's a handy helper and it should be noted somewhere (for e.g. copying) for sure! But does it really matter where one copies from?

Having a link in the file to a comprehensive documentation is more helpful and cleaner for everybody in the end, no?

**Comment by mainman879** [comment]
> Having a link in the file to a comprehensive documentation is more helpful and cleaner for everybody in the end, no?

Is there a link for this documentation in the file itself already? If not, this dummy token could be replaced with a link I suppose.

**Comment by tooomm** [comment]
No link yet, no. This should not be merged as is, as long as we are not decided of course.

<br>

I thought about gathering all useful information including this dummy in a new `Documentation` subpage on the wiki.

If you guys prefer a markdown file in the repo itself that's also fine! Maybe even better and easier to find!

**Comment by Psithief** [comment]
> If you guys prefer a markdown file in the repo itself, that's also fine! Maybe even better and easier to find!

That would be far more convenient than a link.

**Comment by tooomm** [comment]
I would still link such a `documentation.md` file from our xml for ease of use.

e.g. [`https://github.com/Cockatrice/Magic-Token/blob/master/README.md`](https://github.com/Cockatrice/Magic-Token/blob/master/README.md) (but a new file of course)

**Pull request closed without merging**
