### PR TITLE
Version 4.

### PR DESCRIPTION
**Pull request by Psithief**
This doesn't function.

How many new properties are required?

Please review @ctrlaltca

### CODE REVIEW

**Comment by Psithief** [comment]
Changing `picURL` to `picurl` doesn't help.

Is this going to be something ridiculous like `maintype`, `layout` and `coloridentity` are mandatory?

**Comment by ctrlaltca** [comment]
> This doesn't function.
What doesn't work exactly?

I've quickly coded a database converter tool that is able to load a v3 card database and save the v4:
https://github.com/Cockatrice/Cockatrice/pull/3694

**Comment by ctrlaltca** [comment]
Attached is a converted version of the current v3 tokens file produced using the dbconverter tool.

[tokens.xml.txt](https://github.com/Cockatrice/Magic-Token/files/3098697/tokens.xml.txt)

**Comment by Psithief** [comment]
The `sets` element is mandatory?
`maintype` is mandatory?

**Comment by Psithief** [comment]
Apparently my version of Cockatrice didn't update all the way with just one update/install cycle.

**Pull request closed without merging**
