### PR TITLE
add missing tokens from the game night set

### LINKED ISSUE #86: goblin goliath doesn't have a "create x 1/1 goblin tokens" option in its right click menu like most token creators do
<b>System Information:</b>
  

  
_______________________________________________________________________________________

### PR DESCRIPTION
**Pull request by ebbit1q**
also fixes #86

### CODE REVIEW

**Comment by tooomm** [comment]
I assume there are also token prints for GNT that should get linked?

**Comment by ebbit1q** [comment]
apparently not https://scryfall.com/search?q=set%3Agnt+is%3Atoken

**Comment by tooomm** [comment]
20200714 --> #87
20200714a --> #88

**Comment by ebbit1q** [comment]
neither does the set tgnt exist

**Pull request merged**
