### PR TITLE
Remove Parentheses Around Emblem Names

### PR DESCRIPTION
**Pull request by SlightlyCircuitous**

### CODE REVIEW

**Comment by Psithief** [comment]
Why is there no description for this? Why do you want it changed?

**Comment by ebbit1q** [comment]
ah, we discussed this on discord, it looks more uniform with all of the tokens that end with Token and it's the same way they are listed on scryfall.

**Comment by SlightlyCircuitous** [comment]
yes, what ebbit said. It's about uniformity with Scryfall, mainly. I apologize for not including a description in the first place.

**Comment by ebbit1q** [comment]
no news is good news, merging this

**Pull request merged**
