### PR TITLE
mindcrank does not make poison counters

### PR DESCRIPTION
**Pull request by ebbit1q**
(the infect reference is just reminder text)

### CODE REVIEW

**Review by tooomm — APPROVED** [review]
Good catch.

https://scryfall.com/card/ima/220/mindcrank

**Comment by Psithief** [comment]
I didn't even get a chance, geez. 😛

**Comment by ebbit1q** [comment]
do you ever have that moment where you retroactively realize you made a pun that you didn't think about before?

this pr's description is like that, but it's reminder text

**Comment by Psithief** [comment]
Now that you've discovered that, you should edit the description it to put it in italics to make it intentional.

**Pull request merged**
