### PR TITLE
Check links

### PR DESCRIPTION
**Pull request by tooomm**

### CODE REVIEW

**Comment by ebbit1q** [comment]
what's this?

**Comment by tooomm** [comment]
See #131

**Comment by ebbit1q** [comment]
did you accidentally open a new pr?

**Comment by ebbit1q** [comment]
please leave an explanation why you close the pr, otherwise it's hard to track what's going on

**Comment by tooomm** [comment]
It was a mistake on my side, https://github.com/Cockatrice/Magic-Token/pull/131 is the correct one.

**Pull request closed without merging**
