### PR TITLE
wizards to https

### PR DESCRIPTION
**Pull request by tooomm**
wizards finally supports https!

### CODE REVIEW

**Comment by Psithief** [comment]
Supports? or is it required? They are very different terms.

**Comment by tooomm** [comment]
>Supports?

Yes.

>or is it required?

No.

>They are very different terms.

Yes.

>The difference is rather important.

Yes.

Nothing was broken before this change, and nothing will brake after it.
Wizards only managed to allow secure connections in between...

**Comment by Psithief** [comment]
The connection overhead for the security provided by https is not warranted, since these are only image files. If files can still be downloaded by http, we shouldn't change this.

**Comment by tooomm** [comment]
So you want to wait until unsecured http is fully deprecated instead building future proof now?

What's about the 472 https links to mci then? ;)

**Comment by Psithief** [comment]
Once http becomes fully deprecated on the server, what will happen is that the http request will become redirected to a https request. This already happens for magiccards.info, so using the https there is faster.

**Comment by ZeldaZach** [comment]
I see no reason to avoid merging this PR. Always better to secure a link.

**Comment by Psithief** [comment]
No Zach, that is a completely pointless waste of extra electrical power for no benefit to anyone. There is no meaningful communication to secure. These are _public, non-executable resources_.

**Pull request closed without merging**
