### PR TITLE
Move MH2 Construct Token image to Proper Card

### PR DESCRIPTION
**Pull request by SlightlyCircuitous**
While I was looking through the token xml, I found a few things that should probably be changed. 

Not included in the pull is the fact that there's a card called 'Obosh, With The Leggies' listed as Reverse Related in the Companion Section. Is that supposed to be there or is it redundant with 'Obosh, the Preypiercer'?

### CODE REVIEW

**Review by ebbit1q — APPROVED** [review]
nice find, thanks!

**Comment by ebbit1q** [comment]
I assume obosh with the leggies might have been a preview card that had an incomplete name, scryfall adds these cards with funny names sometimes

**Comment by ebbit1q** [comment]
doing a search of these shows we have a couple similar names:
```
"Big Boy Forest Crusher" placeholder for Quartzwood Crasher
"Destoroyah, Perfect Lifeform" alt name for Everquill Phoenix
"What's Kraken" placeholder for Ominous Seas
"Obosh, With The Leggies" placeholder for Obosh, the Preypiercer
"Gigan, Cyberclaw Terror" alt name for Gyruda, Doom of Depths
```

none of these names show up in the xml generated by oracle, they take their primary name and their alt name is ignored, in most cases being overwritten

I propose all of these be removed

**Comment by tooomm** [comment]
@SlightlyCircuitous Thanks for upgrading to the way better Scryfall image as well! ;)

**Pull request merged**
