### PR TITLE
De-Gather all Remaining Links

### PR DESCRIPTION
**Pull request by SlightlyCircuitous**
Now that all the complicated cards were taken care of in https://github.com/Cockatrice/Magic-Token/pull/162, I have run my two algorithms to replace all the other links automatically. I have attached a .txt file (github wouldn't accept a .py) containing the algorithms (and tests) I used to do this.

[degathering_functions.txt](https://github.com/Cockatrice/Magic-Token/files/9031948/degathering_functions.txt)

I borrowed some code from Magic-Spoiler to call the Scryfall API and so, if I am reading the GPL correctly, I had to license that function under GPL; the rest should be able to be (and are) public domain. Please correct me if I have misapplied the license or should not have used this code.

This should close https://github.com/Cockatrice/Magic-Token/issues/149.

### CODE REVIEW

**Comment by ebbit1q** [comment]
the results of running gpl code are not covered by the license, only the code and binary representations of it are, there is no problem including such automated changes in the xml

**Review by ebbit1q — APPROVED** [review]

**Comment by Psithief** [comment]
Useless fact of the day:
The media.wizards.com links are not Gatherer links. Also, tokens didn't get added to Gatherer, except in a number of Duel Decks they added by mistake. 😀

**Comment by ebbit1q** [comment]
true, they are actually from their blog

**Comment by SlightlyCircuitous** [comment]
Damn, that really ruins the "Magic: De-gathering" pun I was using for all my file names. Oh well, they're gone now, whatever they are.

**Pull request merged**
