### PR TITLE
Fixed color for Human Cleric on SOI.

### PR DESCRIPTION
**Pull request by lsmoura**

### CODE REVIEW

**Comment by Daenyth** [comment]
Thanks!

**Comment by Psithief** [comment]
Reverting because whitespace changes.

**Comment by Daenyth** [comment]
Did they break something? Looked right to me. Maybe we should set up a lint build on some CI?

**Comment by Psithief** [comment]
Didn't break anything, it's seems rude to change whitespace and pretend it didn't happen. All those changes except adding a newline to the end of the file were good changes, but it made me realise none of those comments are necessary now.

**Comment by lsmoura** [comment]
Sorry about that. My editor already removes the spaces, I did not tought it was a problem.

**Pull request merged**
